### ISSUE TITLE
SignUp with email

### ISSUE THREAD

**Issue by denscholar** [hngx-org/Panthers-events-backend#10]
Integrate Google sign-up functionality into the application, allowing users to create accounts and sign in using their Google credentials. Google sign-up provides a convenient and secure way for users to join the platform.

### Google Sign-up API Integration:

- Implement Google Sign-in API to enable users to sign up using their Google accounts.
- Ensure that the Google Sign-in API is correctly configured in the project.
- Google Sign-up Button:

- Link the Google-authenticated user to their user profile within the application.
- Ensure that user profiles are automatically created upon Google sign-up.
- Authentication and Authorization:

**Comment by TessyJames28** [comment]
Hi, I will like to be assigned to this task

**Comment by Pythonian** [comment]
Please, i thought Mark said we should only use Google authentication and not the regular email registration?
