### ISSUE TITLE
User profile management-2

### ISSUE THREAD

**Issue by denscholar** [hngx-org/Panthers-events-backend#11]
Create API endpoints for viewing and updating user profiles.
Allow users to upload and update their avatars.
Ensure that profiles are created automatically upon a user signing up

## Acceptance Criteria for Avatar Management:

1. API endpoints allow users to upload and update their avatars.
2. 1. User avatars are securely stored, and a mechanism is in place to prevent unauthorized access to avatars.
3. 2. Avatars can be retrieved by their respective users via the API endpoint.

## Acceptance Criteria for Automatic Profile Creation:

1. User profiles are created automatically upon user registration, ensuring that each user has an associated profile.
2. Newly registered users are assigned default values for user profile attributes (e.g., empty full name, default avatar) until they update their profiles.

**Comment by olatunde2** [comment]
Thanks I started working now
