### ISSUE TITLE
User Login

### ISSUE THREAD

**Issue by MichealCodez** [hngx-org/Panthers-events-backend#12]
1. Create a login endpoint to authenticate users.
2. Generate and return a JWT token upon successful login.

**Comment by fikayo1** [comment]
I can work on this. @denscholar I'd like to be assigned to this.

**Comment by Femi-ID** [comment]
Would also like to work on this 🤞🏾

**Comment by MichealCodez** [comment]
This is a single endpoint and only one person can work on it

@fikayo1 can start working on it already
team lead will assign it to you later

**Comment by fikayo1** [comment]
Alright then, once the open PR (contains the user model and all) is merged I'll complete and open a PR.

**Comment by MichealCodez** [comment]
User model is ready

**Comment by MichealCodez** [comment]
What is your slack handle?

**Comment by fikayo1** [comment]
@fikayo_
