### ISSUE TITLE
User Logout

### ISSUE THREAD

**Issue by MichealCodez** [hngx-org/Panthers-events-backend#13]
1. User Logout API Endpoint
2. Create an endpoint to invalidate the user's token.

**Comment by BobadeKenny** [comment]
@MichealDavid1 @denscholar can I be assigned to this?

**Comment by MichealCodez** [comment]
You can start working on it already 
Team lead will assign it to you later

**Comment by BobadeKenny** [comment]
Alright, thanks

**Comment by MichealCodez** [comment]
what is your slack handle?

**Comment by BobadeKenny** [comment]
Kenny_B
