### ISSUE TITLE
Password Reset

### ISSUE THREAD

**Issue by MichealCodez** [hngx-org/Panthers-events-backend#14]
1. Password Reset and Recovery API Endpoint
2. Implement a "Forgot Password" feature with an API endpoint.
3. Send password reset instructions via email.

**Comment by JesseGreat** [comment]
I will love to do this please

**Comment by MichealCodez** [comment]
Team lead will assign to you later but you can start working on it already

**Comment by JesseGreat** [comment]
Copied that

**Comment by MichealCodez** [comment]
what is your slack handle?

**Comment by MichealCodez** [comment]
If google auth will be used

this issue is off no positive effect
I will close it
