### ISSUE TITLE
User Authentication and Registration-1

### ISSUE THREAD

**Issue by denscholar** [hngx-org/Panthers-events-backend#2]
## Create User Model
1. Define user attributes (e.g., username, email, password_hash).
2. Implement User model with appropriate fields: custom user model

### User attributes are clearly defined and documented, including:
- Username
- Email

### Password hash (securely hashed and stored)
- Each user attribute has a defined purpose and usage within the application.
- Validation rules for user attributes are specified, such as:

Email format validation.
- Password strength requirements (e.g., minimum length, character complexity).
- Any additional user attributes required for the project are identified and documented.

**Comment by Hogbunike** [comment]
I can actually start from here, kindly assign me to this

**Comment by MichealCodez** [comment]
What's up with this issue

How is it going now?
