### ISSUE TITLE
Techies/Group Screen

### ISSUE THREAD

**Issue by techsultann** [hngx-org/Panthers-events-backend#21]
Create the techies screen

**Comment by MichealCodez** [comment]
This is backend bro

I hope you are not making mistake?

**Comment by MichealCodez** [comment]
I mean this repo is for backend

**Comment by techsultann** [comment]
Was not event checking, so there's no repo for mobile?

**Comment by Pythonian** [comment]
I think you should communicate this with team lead. I could recollect Naza talking about two repos (mobile and backend) for each teams. I dont know if that instruction is still in effect.

**Comment by JesseGreat** [comment]
The mobile repo is there, I think he ommitted it

**Comment by F0laf0lu** [comment]
There's a repo created for mobile already check the main panther page
