### ISSUE TITLE
User Authentication and Registration-2

### ISSUE THREAD

**Issue by denscholar** [hngx-org/Panthers-events-backend#3]
## User Login API Endpoint

1. Create a login endpoint to authenticate users.
2. Generate and return a JWT token upon successful login.
3. User Logout API Endpoint
4. Create an endpoint to invalidate the user's token.
5. Password Reset and Recovery API Endpoint
6. Implement a "Forgot Password" feature with an API endpoint.
7. Send password reset instructions via email.

**Comment by MichealCodez** [comment]
I can be part of this

**Comment by denscholar** [comment]
This task #3 has been assigned to you.

**Comment by TessyJames28** [comment]
Is this not a lot of tasks for one person when there are not much to go round
At least one endpoint for one person so the tasks can go around. This is like three endpoints

**Comment by denscholar** [comment]
@TessyJames28 If you have seen my comment somewhere, I said I am still breaking them down. This is just so I keep track of whats going on.

**Comment by MichealCodez** [comment]
Good enough

**Comment by MichealCodez** [comment]
So this is it

1 and 2 is an endpoint

3 and 4 is another

5, 6 and 7 is another
