### ISSUE TITLE
User interaction -1

### ISSUE THREAD

**Issue by denscholar** [hngx-org/Panthers-events-backend#30]
## Acceptance Criteria:

- Accept the unique user identifier (userId) and event identifier (eventId) as URL parameters.
- Verify that the user with userId exists in the database.
- Verify that the event with eventId exists in the database.
- Create an association between the user and the event to indicate interest.
- Return a success response indicating that the user has expressed interest in the event.
- Handle cases where the user or event does not exist.

**Comment by Abas-dev** [comment]
pls who is handling this 

and what is your slack username

**Comment by Dolapo001** [comment]
I am
My slack name is Dolapo
