### ISSUE TITLE
User Interactions-2

### ISSUE THREAD

**Issue by denscholar** [hngx-org/Panthers-events-backend#31]
### Acceptance Criteria:

- Accept the unique user identifier (userId) and event identifier (eventId) as URL parameters.
- Verify that the user with userId exists in the database.
- Verify that the event with eventId exists in the database.
- Remove the association between the user and the event to indicate no interest.
- Return a success response indicating that the user's interest in the event has been removed.
- Handle cases where the user or event does not exist or the user was not previously interested in the event.

**Comment by Abas-dev** [comment]
this is done
