### ISSUE TITLE
user Interraction-5

### ISSUE THREAD

**Issue by denscholar** [hngx-org/Panthers-events-backend#35]
### Acceptance Criteria:

- Accept the unique group identifier (groupId) as a URL parameter.
- Allow users to update group details such as group name and description.
- Validate and save the updated group information in the database.
- Return an appropriate response with the updated group details.
- Handle cases where the requested groupId does not exist or the update fails due to validation errors.

**Comment by MichealCodez** [comment]
What’s the update here?
