### ISSUE TITLE
User Interraction -6

### ISSUE THREAD

**Issue by denscholar** [hngx-org/Panthers-events-backend#36]
### Acceptance Criteria:

- Accept the unique group identifier (groupId) as a URL parameter.
- Check if the group with the provided groupId exists in the database.
- If the group exists, remove it from the database along with its associated members and content.
- Return an appropriate success response indicating successful deletion.
- Handle cases where the requested groupId does not exist.

**Comment by MichealCodez** [comment]
Any luck?
