### ISSUE TITLE
User interraction - 7

### ISSUE THREAD

**Issue by denscholar** [hngx-org/Panthers-events-backend#37]
### Acceptance Criteria:

- Accept the unique group identifier (groupId) and user identifier (userId) as URL parameters.
- Verify that the group with groupId exists in the database.
- Verify that the user with userId exists in the database.
- Add the user to the group as a member.
- Return a success response indicating that the user has been added to the group.
- Handle cases where the group or user does not exist.

**Comment by MichealCodez** [comment]
What’s the update here?

**Comment by gbemike** [comment]
Might need some help

**Comment by MichealCodez** [comment]
Okay what do you need

**Comment by MichealCodez** [comment]
I’m available to help you out
