### ISSUE TITLE
User Interraction - 8

### ISSUE THREAD

**Issue by denscholar** [hngx-org/Panthers-events-backend#38]
### Acceptance Criteria:

- Accept the unique group identifier (groupId) and user identifier (userId) as URL parameters.
- Verify that the group with groupId exists in the database.
- Verify that the user with userId exists in the database.
- Remove the user from the group's list of members.
- Return a success response indicating that the user has been

**Comment by MichealCodez** [comment]
Is this all good now?

**Comment by fikayo1** [comment]
Yeah it is @MichealDavid1 it has been merged

**Comment by MichealCodez** [comment]
Weldon
