### ISSUE TITLE
User Profile Management

### ISSUE THREAD

**Issue by denscholar** [hngx-org/Panthers-events-backend#4]
## User Profile Model

1. Define user profile attributes (e.g., full name, avatar).
2. Implement UserProfile model with appropriate fields.
3. User Profile API Endpoints

## Acceptance Criteria for User Profile Model:
 
1. User profile attributes are clearly defined, including at least:
- Full name
- Avatar (or profile picture)
2. Each user profile attribute has a defined purpose and usage within the application.
3. The UserProfile model is implemented as a separate model and linked to the User model using a one-to-one relationship or another appropriate method.
4. The UserProfile model includes fields corresponding to the defined user profile attributes, with appropriate data types and constraints.
5. User profile data is associated with the correct user accounts, ensuring that each user has a unique profile.

## Acceptance Criteria for User Profile API Endpoints:

1. API endpoints for viewing and updating user profiles are available and functional.
2. The API endpoint for viewing user profiles is accessible via HTTP GET requests.
3. The API endpoint for updating user profiles is accessible via HTTP PUT or PATCH requests.
4. User authentication is required to access and update user profiles.

**Comment by olatunde2** [comment]
Please I want to be here
