### ISSUE TITLE
Event Management

### ISSUE THREAD

**Issue by denscholar** [hngx-org/Panthers-events-backend#5]
## Event Model
- Define fields for the Event model (e.g., title, date, time, location).
- Implement an Event model with appropriate relationships.
- Event Creation API Endpoint
- Create an API endpoint for event creation with relevant details (title, date, time, location, etc.).
- Event Editing and Deletion API Endpoints
- Develop API endpoints for updating and deleting events.

**Comment by Nathan-Yinka** [comment]
I will be handling this.

**Comment by Konlan21** [comment]
I can work on part of this. CRUD operations on the api endpoints
