### ISSUE TITLE
Group Management

### ISSUE THREAD

**Issue by denscholar** [hngx-org/Panthers-events-backend#6]
## Group Model

- Define fields for the Group model (e.g., name, description).
- Implement a Group model with appropriate relationships.
- Group Creation API Endpoint
- Create an API endpoint for group creation.

## Acceptance Criteria for Group Model:

1. The Group model is created as a separate model in the application.
2. The Group model includes the following fields:
- Group name: A unique name or title for the group.
- Group description: A brief description or summary of the group's purpose.
- Group members: A many-to-many relationship with User objects to represent group members.
- Group creation date: A timestamp indicating when the group was created.
- The Group model enforces constraints and validations for its fields:

3. Group name is unique among all groups in the system.
- Group name and description have appropriate character limits.

**Comment by Nazzcodek** [comment]
I will work on this

**Comment by solutionasepe** [comment]
can i work on this also?
