### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by denscholar** [hngx-org/Panthers-events-backend#7]
## Comment Model:

- Define fields for the Comment model (e.g., text, timestamp, user, event/post reference).
- Implement a Comment model with appropriate relationships.
- Comment Creation API Endpoint:
- Create an API endpoint for users to create comments on events.
- Validate comment content and user authorization.
- Store the comment in the database with a reference to the associated event or post.

**Comment by F0laf0lu** [comment]
I'd like to take up this task

**Comment by Paschal-ike** [comment]
I'd like to work on this

**Comment by johndiginee** [comment]
Please, I'd like to work on this as well.

**Comment by F0laf0lu** [comment]
Comments model are up already
