### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by denscholar** [hngx-org/Panthers-events-backend#9]
## PI Documentation Platform:

- Choose a platform or tool for hosting your API documentation, such as Swagger, Postman, or a dedicated documentation website.
- Set up the chosen platform and configure it for your project.
- Create an introductory section that provides an overview of your API, its purpose, and key features.
- List and describe each API endpoint available in your application.

**Comment by johndiginee** [comment]
Hello, I would like to be assigned to this task.

**Comment by johndiginee** [comment]
Hi @denscholar, Please you can close this issue since you've done it already then reassign me to another open issue if you don't mind. Thank you
